default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: socify_development
  host: 18.136.120.134
  username: postgres
  password: Tuanphong0402
  
test:
  <<: *default
  database: socify_test
  host: 18.136.120.134
  username: postgres
  password: Tuanphong0402

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
