default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: socify_development
  host: <%= ENV['DATABASE_LOCAL_HOST'] %>
  username: <%= ENV['DATABASE_LOCAL_USER'] %>
  password: <%= ENV['DATABASE_LOCAL_PASSWORD'] %>
  
test:
  <<: *default
  database: socify_test
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_LOCAL_USER'] %>
  password: <%= ENV['DATABASE_LOCAL_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_PROD_URL'] %>
