default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: socify_development
  host: localhost
  username:
  password:
  
test:
  <<: *default
  database: socify_test
  host: localhost
  username:
  password:

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
